name: version add
on: 
  workflow_dispatch:
    inputs:
      chain:
        description: "Chain to update"
        required: true
        default: "None"
        type: string

      tag-height-proposal:
        description: "Tag, Height and Proposal. If the upgrade is not consensus break, leave height and proposal to -1."
        required: true
        default: '{
          "tag": "-1",
          "height": -1,
          "proposal": -1
        }'
        type: string

      cosmos_sdk_version:
        description: "CosmosSDK version. Not required"
        required: false
        default: "0.46"
        type: string

      consensus:
        description: "Consensus. Not required"
        required: false
        default: '{
          "type": "tendermint",
          "version": "0.34"
        }'
        type: string
      
      cosmwasm_version:
        description: "CosmWasm version. Not required"
        required: false
        default: "0.46"
        type: string
      
      cosmwasm_path:
        description: "Default path to wasm directory. Not required"
        required: false
        default: "0.46"
        type: string
      
      ibc_go_version:
        description: "IBC-go version. Not required"
        required: false
        default: "4.3.0"
        type: string

      ics_enabled:
        description: "List of enabled ICS. Not required"
        required: false
        default: '["ics20-1"]'
        type: string

      binaries:
        description: "Binaries list. Enter a list of binaries in JSON format"
        required: true
        default: '{
          "linux/amd64": "https://github.com/regen-network/regen-ledger/releases/download/v5.0.0/regen-ledger_5.0.0_linux_amd64.zip",
          "linux/arm64": "https://github.com/regen-network/regen-ledger/releases/download/v5.0.0/regen-ledger_5.0.0_linux_arm64.zip",
          "darwin/amd64": "https://github.com/regen-network/regen-ledger/releases/download/v5.0.0/regen-ledger_5.0.0_darwin_amd64.zip",
          "darwin/arm64": "https://github.com/regen-network/regen-ledger/releases/download/v5.0.0/regen-ledger_5.0.0_darwin_arm64.zip"
        }'
        type: string

jobs:
  validate-data:
    name: Validate Data
    runs-on: ubuntu-latest
    steps:
      - name: Validate Chain
        run: |
          chain=${{ github.event.inputs.chain }}
          tag=$(echo '${{ github.event.inputs.tag-height-proposal }}' | jq '.tag')
          height=$(echo '${{ github.event.inputs.tag-height-proposal }}' | jq '.height')
          proposal=$(echo '${{ github.event.inputs.tag-height-proposal }}' | jq '.proposal')
          cosmos_sdk_version=${{ github.event.inputs.cosmos_sdk_version }}
          consensus='${{ github.event.inputs.consensus }}'
          cosmwasm_version=${{ github.event.inputs.cosmwasm_version }}
          cosmwasm_path=${{ github.event.inputs.cosmwasm_path }}
          ibc_go_version=${{ github.event.inputs.ibc_go_version }}
          ics_enabled='${{ github.event.inputs.ics_enabled }}'
          binaries='${{ github.event.inputs.binaries }}'

          echo $chain
          echo $tag
          echo $height
          echo $proposal
          echo $cosmos_sdk_version
          echo $consensus
          echo $cosmwasm_version
          echo $cosmwasm_path
          echo $ibc_go_version
          echo $ics_enabled
          echo $binaries

  # generate-other-data:
  #   name: Generate other data
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Gen recommend_version
  #       run: |
  #         ech
  print:
    name: Print all input in JSON format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: print
        run: |
          echo "Name: ${{ github.event.inputs.name }}"
          echo "Tag: ${{ github.event.inputs.tag }}"
          echo "Height: ${{ github.event.inputs.height }}"
          echo "Recommend Version: ${{ github.event.inputs.recommend_version }}"
          echo "Compatible versions: ${{ github.event.inputs.compatible_versions }}"
          echo "Binaries: ${{ github.event.inputs.binaries }}"
          echo "CosmosSDK version: ${{ github.event.inputs.cosmos_sdk_version }}"
          echo "IBC-GO version: ${{ github.event.inputs.ibc_go_version }}"
          echo "Consensus: ${{ github.event.inputs.consensus }}"