name: version add
on: 
  workflow_dispatch:
    inputs:
      name: 
        description: "Name of the new version"
        required: true
        default: "v1.0.0"
        type: string
      
      tag:
        description: "Version tag. Example: v1.0.0"
        required: true
        default: "v1.0.0"
        type: string
      
      height:
        description: "Height of the version upgrade"
        required: true
        default: "123456"
        type: string
      
      recommend_version:
        description: "Recommend Version"
        required: true
        default: "v1.0.0"
        type: string

      compatible_versions:
        description: "Compatible versions. Enter a list of compatible versions in JSON format, separated by commas"
        required: true
        default: "['v1.0.0', 'v1.0.1']"
        type: string

      binaries:
        description: "Binaries list. Enter a list of binaries in JSON format"
        required: true
        default: "{
          'linux/amd64': 'https://github.com/regen-network/regen-ledger/releases/download/v5.0.0/regen-ledger_5.0.0_linux_amd64.zip',
          'linux/arm64': 'https://github.com/regen-network/regen-ledger/releases/download/v5.0.0/regen-ledger_5.0.0_linux_arm64.zip',
          'darwin/amd64': 'https://github.com/regen-network/regen-ledger/releases/download/v5.0.0/regen-ledger_5.0.0_darwin_amd64.zip',
          'darwin/arm64': 'https://github.com/regen-network/regen-ledger/releases/download/v5.0.0/regen-ledger_5.0.0_darwin_arm64.zip'
        }"
        type: string
      
      cosmos_sdk_version:
        description: "CosmosSDK version. Not required"
        required: false
        default: "0.46"
        type: string

      ibc_go_version:
        description: "IBC-GO version. Not required"
        required: false
        default: "5.2"
        type: string

      consensus:
        description: "Consensus. Not required"
        required: false
        default: "{
          'type': 'tendermint',
          'version': '0.34'
        }"
        type: string

jobs:
  print:
    name: Print all input in JSON format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: print
        run: |
          echo "Name: ${{ github.event.inputs.name }}"
          echo "Tag: ${{ github.event.inputs.tag }}"
          echo "Height: ${{ github.event.inputs.height }}"
          echo "Recommend Version: ${{ github.event.inputs.recommend_version }}"
          echo "Compatible versions: ${{ github.event.inputs.compatible_versions }}"
          echo "Binaries: ${{ github.event.inputs.binaries }}"
          echo "CosmosSDK version: ${{ github.event.inputs.cosmos_sdk_version }}"
          echo "IBC-GO version: ${{ github.event.inputs.ibc_go_version }}"
          echo "Consensus: ${{ github.event.inputs.consensus }}"
