on: [pull_request, workflow_dispatch]
name: PR workflow
jobs:
  validate_chainjson:
    name: Validate edited assetlist.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ajv-cli
        run: npm install -g ajv-cli@latest
        
      - name: Validate Assetlist.json schema
        run: ajv -s ./assetlist.schema.json -d .*assetlist.json$
