on: [pull_request, workflow_dispatch]
name: PR workflow
jobs:
  validate_chainjson:
    name: Validate edited assetlist.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ajv-cli
        run: npm install -g ajv-cli
        
      - name: Download JSON Schema meta-schema
        run: curl https://json-schema.org/draft-07/schema -o ./draft-07-schema.json
        
      - name: Validate Assetlist.json schema
        run: ajv -s ./assetlist.schema.json -d .*assetlist.json$ --meta=inline://./draft-07-schema.json
